import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';
import './globals.css';

import TRPCReactProvider from '@/trpc/client';
import { Toaster } from 'sonner';

import { NuqsAdapter } from 'nuqs/adapters/next/app';

const dmSans = DM_Sans({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Multitenant',
  description: 'Generated by Multitenant',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSans.className} antialiased`}>
        <NuqsAdapter>
          <TRPCReactProvider>
            <Toaster />
            {children}
          </TRPCReactProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
